### PR TITLE
Implementing and Fixing All Racing Achievements

### LINKED ISSUE #218: Some racing missions not working
### 

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

I've tried many times, they just don't work:

"No Wreckin'"
 
"Dragonscourge"

### Reproduction steps

take these missions when you get to them, race. Counters for the dragon eggs wont go up, and missions like No Wreckin' will not complete.

### Expected Behavior

missions should be completable as normal

### Environment

ubuntu server

### PR DESCRIPTION
**Pull request by EmosewaMC**
Previously, most racing achievements either did not progress correctly or did not progress at all.  This PR fixes all of these tasks and allows them all to progress properly.  Bugs unrelated to the achievements functionality will not be in this PR (Ex. Lap times are not properly tracked for the first and possibly second lap making some lap times only possible on lap 3).  

A new enum file has been added that contains named taskparam1 to reduce the amount of magic numbers that are in the original implementation.  

This PR also fixes general grammatical errors found while working on this PR and also has alphabetized includes in files I was working in.
Fixes #218

### CODE REVIEW

File: dGame/dMission/RacingTaskParam.h [hunk 1]
```diff
@@ -0,0 +1,20 @@
+#pragma once
+
+#include <cstdint>
+
+enum class RacingTaskParam : int64_t {
```
Comment (Jettford) [inline dGame/dMission/RacingTaskParam.h:5]: This enum shouldn't be its own file, should be in one of the racing components imo

Comment (Jettford) [reply dGame/dMission/RacingTaskParam.h:5]: or dCommonVars

Comment (Wincent01) [reply dGame/dMission/RacingTaskParam.h:5]: I believe putting it into its own file is fine, would prefer that rather than clod up dCommonVars even more

Comment (averysumner) [reply dGame/dMission/RacingTaskParam.h:5]: Whatever you do, do not put it in dCommonVars.

Comment (Jettford) [reply dGame/dMission/RacingTaskParam.h:5]: Lol, I just thought that was where all enums were slapped

File: dGame/dMission/RacingTaskParam.h [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+    RACING_TASK_PARAM_FINISH_WITH_PLACMENT = 1,             //<! A task param for finishing with a specific placement.
```
Comment (Marcono1234) [inline dGame/dMission/RacingTaskParam.h:6]: Looks like there is a typo (first 'e' of 'placement' is missing): <code>RACING_TASK_PARAM_FINISH_WITH_PLAC<ins>E</ins>MENT</code>

File: dGame/dMission/RacingTaskParam.h (hunk 1 above)
Comment (EmosewaMC) [reply dGame/dMission/RacingTaskParam.h:5]: Since MissionTaskType is in its own file I think this fits well in its own file because these values are only used for racing.  Have updated the enum to be a int32_t as I recall that enums shouldnt be of size 64.

File: dGame/dMission/RacingTaskParam.h (hunk 2 above)
Comment (EmosewaMC) [reply dGame/dMission/RacingTaskParam.h]: Fixed.  Good spot!

**Comment by EmosewaMC** [comment]
I have tested this rigorously and have not had any issues or hard crashes.  Whenever there is some time for reviews @Wincent01 I know you wrote the racing control components so when you have time to review this that'd be great!  Any other reviews are also appreciated.

**Review by Jettford — APPROVED** [review]
