### PR TITLE
Fix an issue where quickbuilds were sometimes unbuildable

### LINKED ISSUE #122: Quickbuild sometimes just stops working. Even for other players
image

### PR DESCRIPTION
**Pull request by EmosewaMC**
Address an issue where quickbuilds would become unbuildable.  The main issue lied within serializing parent/child info too often for some reason / serializing it when the info wasnt dirty.  Only serializing this info when it is actually dirty and has changed has addressed the issue and allows quickbuilds to never break.

Since this PR changes how Parents and Children work the following was tested.

First I tested the 100% consistent reproduction in Avant Gardens (finish a build, spawn a build, finish the spawned build, original build respawns, serialize spawned build) and the build never became unbuildable.  The engineers turret that is spawned with the helmet with the 50% consistent reproduction had never encountered the issue where it was unbuildable.  Racing still works as well as spawning a car from your backpack.  Pets still spawn and set their owner correctly and taming them still builds the item as intended.

Fixes #122

### CODE REVIEW

**Comment by EmosewaMC** [comment]
I am seeking a few reviewers to verify these changes and ensure that I have not done something critically wrong or that this breaks something crucial.

File: dGame/Entity.cpp [hunk 1]
```diff
@@ -974,8 +975,11 @@ void Entity::WriteBaseReplicaData(RakNet::BitStream* outBitStream, eReplicaPacke
 		}
 		else outBitStream->Write0(); //No GM Level
 	}
-	outBitStream->Write((m_ParentEntity != nullptr || m_ChildEntities.size() > 0));
-	if (m_ParentEntity || m_ChildEntities.size() > 0) {
+	
+	// Only serialize parent / child info should the info be dirty (changed) or if this is the construction of the entity.
+	outBitStream->Write((m_ParentEntity != nullptr || m_ChildEntities.size() > 0) && (m_IsParentChildDirty || packetType == PACKET_TYPE_CONSTRUCTION));
```
Comment (Wincent01) [inline dGame/Entity.cpp:980]: Maybe eval this long Boolean expression to a variable and use that, for readability.

**Review by Wincent01 — APPROVED** [review]
Great find!

File: dGame/dComponents/RebuildComponent.cpp [hunk 2]
```diff
@@ -22,6 +22,18 @@ RebuildComponent::RebuildComponent(Entity* entity) : Component(entity) {
...
 		m_Precondition = new PreconditionExpression(GeneralUtils::UTF16ToWTF8(checkPreconditions));
 	}
+
+	// Should a setting that has the build activator position exist, fetch that setting here and parse it for position.
+	// It is assumed that the user who sets this setting uses the correct character delimiter (character 31)
+	auto positionAsVector = GeneralUtils::SplitString(m_Parent->GetVarAsString(u"rebuild_activators"), 31);
+	if (positionAsVector.size() == 3) {
+		m_ActivatorPosition.x = std::stof(positionAsVector[0]);
+		m_ActivatorPosition.y = std::stof(positionAsVector[1]);
+		m_ActivatorPosition.z = std::stof(positionAsVector[2]);
```
Comment (Xiphoseer) [inline dGame/dComponents/RebuildComponent.cpp:32]: Can you add a try/catch around these? bad config values shouldn't cause exceptions

File: dGame/Entity.cpp (hunk 1 above)
Comment (EmosewaMC) [reply dGame/Entity.cpp:980]: It is the exact same boolean no?  Simplifying will be applied in the morning though to make this easier to read :)

File: dGame/dComponents/RebuildComponent.cpp (hunk 2 above)
Comment (EmosewaMC) [reply dGame/dComponents/RebuildComponent.cpp:32]: Yeah sure.  Will toss those in so they default to using the quickbuilds spawn point should the position be bad

File: dGame/dComponents/RebuildComponent.cpp [hunk 3]
```diff
@@ -22,6 +22,18 @@ RebuildComponent::RebuildComponent(Entity* entity) : Component(entity) {
 	{
 		m_Precondition = new PreconditionExpression(GeneralUtils::UTF16ToWTF8(checkPreconditions));
 	}
+
+	// Should a setting that has the build activator position exist, fetch that setting here and parse it for position.
+	// It is assumed that the user who sets this setting uses the correct character delimiter (character 31)
+	auto positionAsVector = GeneralUtils::SplitString(m_Parent->GetVarAsString(u"rebuild_activators"), 31);
```
Comment (Xiphoseer) [inline dGame/dComponents/RebuildComponent.cpp:28]: not that it matters, i think 0x1F would feel less magic here than 31

File: dGame/dComponents/RebuildComponent.cpp (hunk 2 above)
Comment (Wincent01) [reply dGame/dComponents/RebuildComponent.cpp:32]: Use GeneralUtils::TryParse

**Comment by Jettford** [comment]
I am good to approve this once the already mentioned config parsing is resolved but other then that LGTM.

**Review by aronwk-aaron — COMMENTED** [review]
Agree with the changes noted by others. Will approve once those have been addressed

**Review by DarwinAnim8or — APPROVED** [review]

**Comment by aronwk-aaron** [comment]
Wont this fix cover #123 as well, since that's the result of this serialization being incorrect?

**Comment by EmosewaMC** [comment]
The addressed feedback has been implemented and all tests have passed once again.  I am glad we are finally able to have solved this issue
