### PR TITLE
Fix: Pets can no longer dig treasure without completing Bella Pepper's "Lost Tags" mission

### LINKED ISSUE #535: BUG: Pet Digs don't require completion of Bella Pepper's Mission
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

427c4a8c33fdb8eca06abd49477e70816f00530b

### Issue Description

In Live, Pet Digs were locked out from use until you learned about them from Bella Pepper in Pet Cove. This is not the case in DLU.

### Reproduction Steps

* Earn pet taming from Coalessa
* Do not speak to Bella Pepper
* Tame your first pet
* Note that all pet digs in the game have been activated

### Expected Behavior

image

Pet digs should be locked out until Bella's quest is completed. This message can be seen briefly at 9:55 in Lego Universe (Part 23) 

https://youtu.be/JHqlfK-NaMA?t=595

### Environment

Windows 11 Client, Linux Server

### PR DESCRIPTION
**Pull request by jadebenn**
Fixes #535. Tested by playing character at Pet Cove who had not completed mission, and then switching to another character who had. Pet would not dig up treasure on the first character, but would on the second. Also took the first character to the Advent Gardens pet bouncer dig and found it was unable to dig (which is desired behavior).

### CODE REVIEW

**Comment by jadebenn** [comment]
Just to be extra sure, I went ahead and completed the quest on the first character, trying to dig before and after with no relogging or anything else that could screw things up. Didn't work before I completed the quest, but afterwards it did.

File: dGame/dComponents/PetComponent.cpp [hunk 1]
```diff
@@ -439,9 +441,15 @@ void PetComponent::Update(float deltaTime) {
 		}
 	}
 
+	auto* missionComponent = owner->GetComponent<MissionComponent>();
+	if (missionComponent == nullptr) return;
+
+	// Determine if "Lost Tags" has been completed and digging has been unlocked
+	const bool digUnlocked = (missionComponent->GetMissionState(842) == eMissionState::COMPLETE);
```
Comment (EmosewaMC) [inline dGame/dComponents/PetComponent.cpp:448]: Extra parenthesis around the condition, I would also define this 842 to be Lost_Tags in dCommonVars.h since it may be used as a check in other places

File: dGame/dComponents/PetComponent.cpp [hunk 2]
```diff
@@ -439,9 +441,15 @@ void PetComponent::Update(float deltaTime) {
 		}
 	}
 
+	auto* missionComponent = owner->GetComponent<MissionComponent>();
+	if (missionComponent == nullptr) return;
```
Comment (EmosewaMC) [inline dGame/dComponents/PetComponent.cpp:445]: Can simplify to if (!missionComponent) return;

File: dGame/dComponents/PetComponent.cpp (hunk 1 above)
Comment (EmosewaMC) [reply dGame/dComponents/PetComponent.cpp:448]: This would also allow you to remove the comment since you are basically moving that into a constant :)

Comment (jadebenn) [reply dGame/dComponents/PetComponent.cpp:448]: Wouldn't that paste it into every bit of code that includes that header file? I'm not sure that value is really needed outside this one check.

Comment (EmosewaMC) [reply dGame/dComponents/PetComponent.cpp:448]: hm yeah i dont see it used outside of this file, ill leave it up to you if you want to define the number in an anonymous enum, const variable or leave it alone.

Comment (EmosewaMC) [reply dGame/dComponents/PetComponent.cpp:448]: I'll also note, dCommonVars.h is pre-compiled, its already included in every translation unit anyways

**Review by EmosewaMC — APPROVED** [review]

**Review by Wincent01 — APPROVED** [review]
