### PR TITLE
Fix initial character XML being malformed

### LINKED ISSUE #322: BUG: Initial character XML data is malformed
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

It looks like the initial character XML data is malformed. There seems to be a space missing between the `lzrw` and the `stt` attribute:
```
...  lzrw="0.7126"stt="0;0; ...
```

The server itself does not seem to care, but some code editors complain about this.

Example XML data, obtained from `/data_download` endpoint of AccountManager:
```xml
<obj v="1"><mf hc="15" hs="8" hd="0" t="10" l="8" hdc="0" cd="35" lh="28421136" rh="27973828" es="37" ess="13" ms="7"/><char acct="2" cc="0" gm="0" ft="0" llog="1640830714" ls="0" lzx="-626.5847" lzy="613.3515" lzz="-28.6374" lzrx="0.0" lzry="0.7015" lzrz="0.0" lzrw="0.7126"stt="0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;"></char><dest hm="4" hc="4" im="0" ic="0" am="0" ac="0" d="0"/><inv><bag><b t="0" m="20"/><b t="1" m="240"/><b t="2" m="240"/><b t="3" m="240"/></bag><items><in t="0"><i l="5784" id="1152921508901814281" s="0" c="1" eq="1" b="1"/><i l="2522" id="1152921508901814282" s="1" c="1" eq="1" b="1"/></in></items></inv><lvl l="1" cv="1" sb="500"/><flag></flag></obj>
```

I assume this can be fixed by adding a leading space to the string written here, but I am not completely sure:
https://github.com/DarkflameUniverse/DarkflameServer/blob/0a7d9c46eba551b5e2f908caf9c689f4139bffb4/dGame/UserManager.cpp#L295

Would it make sense to use `tinyxml2` here for writing the initial XML to make the code less error-prone?

### Reproduction steps

1. Create a new character
2. Directly afterwards, without having joined the game yet, download the character data from the `/data_download` endpoint of AccountManager
3. Inspect the XML data
:x: The data is malformed, a space is missing between the `lzrw` and the `stt` attribute

### Expected Behavior

XML data should be wellformed

### Environment

Windows 10, WSL 2

(environment should not matter)

### PR DESCRIPTION
**Pull request by Marcono1234**
Fixes #322

XML was missing a space between attributes `lzrw` and `stt`.

Tested this roughly and it seems to work as expected. I did not change the code to use tinyxml2 because I am not familiar enough with C++; sorry. No worries in case you don't want to merge this pull request.

### CODE REVIEW

**Comment by Jettford** [comment]
That is an attribute inside of an element, there should be a space there.

File: dGame/UserManager.cpp [hunk 1]
```diff
@@ -292,7 +292,7 @@ void UserManager::CreateCharacter(const SystemAddress& sysAddr, Packet* packet)
         
         xml << "<char acct=\"" << u->GetAccountID() << "\" cc=\"0\" gm=\"0\" ft=\"0\" llog=\"" << time(NULL) << "\" ";
         xml << "ls=\"0\" lzx=\"-626.5847\" lzy=\"613.3515\" lzz=\"-28.6374\" lzrx=\"0.0\" lzry=\"0.7015\" lzrz=\"0.0\" lzrw=\"0.7126\"";
```
Comment (Xiphoseer) [inline dGame/UserManager.cpp:294]:
```suggestion
        xml << "ls=\"0\" lzx=\"-626.5847\" lzy=\"613.3515\" lzz=\"-28.6374\" lzrx=\"0.0\" lzry=\"0.7015\" lzrz=\"0.0\" lzrw=\"0.7126\" ";
```

**Comment by Marcono1234** [comment]
> That is an attribute inside of an element, there should be a space there.

Are you requesting a change for this pull request, or are you justifying the change made by this pull request?

File: dGame/UserManager.cpp (hunk 1 above)
Comment (Marcono1234) [reply dGame/UserManager.cpp]: Ok, I have changed line 290 & 291 to use this style as well.

**Comment by Jettford** [comment]
> Are you requesting a change for this pull request, or are you justifying the change made by this pull request?

I am not going to lie to you, I read it the wrong way around, I thought you removed the space. My bad :smile:

**Review by Xiphoseer — APPROVED** [review]
LGTM
