### PR TITLE
Fix racing imagination loss on death

### LINKED ISSUE #1005: BUG: Racing boost does not reset properly on smashing
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

6d989f3

### Issue Description

After crashing a vehicle during a race with some boost saved up, the boost bar visually drains, although the full charge is still present. 

### Reproduction Steps

get some boost powerups, crash your vehicle, observe that the bar visually has drained but pressing the spacebar still gives the full boost

### Expected Behavior

https://youtu.be/sfllNjjNYrM?t=128

looks like you're supposed to lose half of the stored boost on respawn

### Environment

ubuntu server

### PR DESCRIPTION
**Pull request by EmosewaMC**
Fixes #1005 

Properly implements losing half you imagination, rounded up to the nearest 10.  

Tested that imagination is lost properly.

### CODE REVIEW

File: dGame/dGameMessages/GameMessages.cpp [hunk 1]
```diff
@@ -4395,6 +4395,24 @@ void GameMessages::SendRacingResetPlayerToLastReset(LWOOBJID objectId, LWOOBJID
...
 }
 
+void GameMessages::SendSetResurrectRestoreValues(Entity* targetEntity, const SystemAddress& playerSysAddr, int32_t armorRestore, int32_t healthRestore, int32_t imaginationRestore) {
+	CBITSTREAM;
+	CMSGHEADER;
+
+	bitStream.Write(targetEntity->GetObjectID());
+	bitStream.Write(GAME_MSG::GAME_MSG_SET_RESURRECT_RESTORE_VALUES);
+	
+	bitStream.Write(armorRestore != 1);
```
Comment (aronwk-aaron) [inline dGame/dGameMessages/GameMessages.cpp:4405]: should be != -1

File: dGame/dGameMessages/GameMessages.cpp [hunk 2]
```diff
@@ -4395,6 +4395,24 @@ void GameMessages::SendRacingResetPlayerToLastReset(LWOOBJID objectId, LWOOBJID
...
+	if (armorRestore != 1) bitStream.Write(armorRestore);
+
+	bitStream.Write(healthRestore != 1);
```
Comment (aronwk-aaron) [inline dGame/dGameMessages/GameMessages.cpp:4408]: should be != -1

**Review by aronwk-aaron — CHANGES_REQUESTED** [review]

**Comment by EmosewaMC** [comment]
Imagination is properly reduced to half your current imagination, rounded to the nearest 10.
Visuals are correctly updated client side upon respawn.

**Review by aronwk-aaron — APPROVED** [review]

**Review by Wincent01 — APPROVED** [review]
