### PR TITLE
fix: Animated deaths not playing

### LINKED ISSUE #1222: BUG: Enemies with special death animations do not get to play the animation before being destructed
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

All

### Issue Description

Some enemies in LU like #515 and some alpha enemies are supposed to play an animation on death, however we currently do not implement death_behavior correctly, and as such, these enemies do not play their animation before being destructed from the server.

### Reproduction Steps

1 Finish a property mission
2 turn the mission in
3 property guard does not get vacuumed away but rather gets destructed instantly

### Expected Behavior

Property guard gets vacuumed away fully before the destruction is sent

### Environment

All

### PR DESCRIPTION
**Pull request by EmosewaMC**
Fixes #1222

addresses an issue where the death behavior of a destructible component was not being respected and enemies with destroyable components that had special death animations were not able to play the animation on death.  This pr adds in the hardcoded constant the client uses for the same metric of 12 seconds.

Tested that claiming Nimbus Rock and completing the property guards mission allows him to vacuum away and then network the destruction packet 12 seconds later.

### CODE REVIEW

File: dScripts/ai/PROPERTY/AgPropguards.cpp [hunk 1]
```diff
@@ -18,7 +18,7 @@ void AgPropguards::OnMissionDialogueOK(Entity* self, Entity* target, int mission
 		&& !character->GetPlayerFlag(flag)) {
 		// If the player just started the mission, play a cinematic highlighting the target
 		GameMessages::SendPlayCinematic(target->GetObjectID(), u"MissionCam", target->GetSystemAddress());
-	} else if (missionState == eMissionState::COMPLETE_READY_TO_COMPLETE) {
+	} else if (missionState == eMissionState::READY_TO_COMPLETE) {
```
Comment (EmosewaMC) [inline dScripts/ai/PROPERTY/AgPropguards.cpp:21]: Yes this is correct now.  Live script uses 4, not 12 here.

**Review by Wincent01 — APPROVED** [review]
