### PR TITLE
Fix race exit dialogue always exiting

### LINKED ISSUE #1048: BUG: Pressing red X on exit race prompt exits the race
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

5412501

### Issue Description

.

### Reproduction Steps

Enter a race, press the x in the top right corner, press the red x for "no"

### Expected Behavior

prompt should close and nothing should happen

### Environment

ubuntu server

### PR DESCRIPTION
**Pull request by aronwk-aaron**
Fixes #1048 
Tested that closing the dialog via esc, the x in the top right, or the big red x doesn't exit the race 
Tested that the green check button does exit the race

### CODE REVIEW

File: dGame/dComponents/RacingControlComponent.cpp [hunk 1]
```diff
@@ -405,7 +404,7 @@ void RacingControlComponent::HandleMessageBoxResponse(Entity* player,
 				missionComponent->Progress(eMissionTaskType::RACING, dZoneManager::Instance()->GetZone()->GetWorldID(), (LWOOBJID)eRacingTaskParam::LAST_PLACE_FINISH); // Finished first place in specific world.
 			}
 		}
-	} else if (id == "ACT_RACE_EXIT_THE_RACE?" || id == "Exit") {
+	} else if (id == "ACT_RACE_EXIT_THE_RACE?" && button == 1) {
```
Comment (EmosewaMC) [inline dGame/dComponents/RacingControlComponent.cpp:407]: Could we get a variable / const for this number?

**Review by EmosewaMC — APPROVED** [review]

**Review by Wincent01 — APPROVED** [review]
