### PR TITLE
fix: not exiting shooting gallery when clicking activity close button

### LINKED ISSUE #436: BUG: Gnarled Forest Cannon Cove Exploit
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### Issue Description

Clicking the "X" exit instance button in the top right corner and selecting the X/No option causes the instance to soft reset itself, resulting in additional targets from the previous instance spawning. This allows a player to easily obtain significantly higher scores than normally possible.

Under some circumstances, this can crash the instance.

### Reproduction steps

Enter the instance.

Click the Exit button in the top right corner, but click the no option to remain in the instance.

Wait several seconds.

Click the Start button to begin the instance.

Additionally you can perform this exploit while the instance is in progress. The issue appears to be caused specifically by clicking the no option for exiting the instance.

### Expected Behavior

Not this.

### Environment

Save the environment.
Plant some trees.
Touch some grass.

### PR DESCRIPTION
**Pull request by aronwk-aaron**
Fixes #436
Fixes crash when replaying as well
Fixed replaying

### CODE REVIEW

**Comment by aronwk-aaron** [comment]
Tested that the game can't be started multiple times
Tested that exiting now leaves the instance
Tested that replaying works

**Review by Wincent01 — DISMISSED** [review]

File: dGame/dGameMessages/GameMessages.cpp [hunk 1]
```diff
@@ -6204,3 +6205,18 @@ void GameMessages::SendShowBillboardInteractIcon(const SystemAddress& sysAddr, L
...
+	bool canceled = false;
+	inStream->Read(canceled);
+	if (!canceled) return;
+
+	LWOOBJID player_id = LWOOBJID_EMPTY;
+	inStream->Read(player_id);
+	auto player = EntityManager::Instance()->GetEntity(player_id);
+	if (!entity || !player) return;
+
+	for (auto* shootingGallery : EntityManager::Instance()->GetEntitiesByComponent(eReplicaComponentType::SHOOTING_GALLERY)) {
```
Comment (EmosewaMC) [inline dGame/dGameMessages/GameMessages.cpp:6219]: This GM is not sent by _any_ other activity?  Could you confirm this?

File: dScripts/ai/MINIGAME/SG_GF/SERVER/SGCannon.h [hunk 2]
```diff
@@ -63,12 +63,11 @@ class SGCannon : public ActivityManager {
...
 	void OnFireEventServerSide(Entity* self, Entity* sender, std::string args, int32_t param1, int32_t param2, int32_t param3) override;
-	void OnActivityStateChangeRequest(Entity* self, LWOOBJID senderID, int32_t value1,
-		int32_t value2, const std::u16string& stringValue) override;
-	void OnMessageBoxResponse(Entity* self, Entity* sender, int32_t button, const std::u16string& identifier,
-		const std::u16string& userData) override;
+	void OnActivityStateChangeRequest(Entity* self, LWOOBJID senderID, int32_t value1, int32_t value2, const std::u16string& stringValue) override;
+	void OnMessageBoxResponse(Entity* self, Entity* sender, int32_t button, const std::u16string& identifier, const std::u16string& userData) override;
 	void OnActivityTimerDone(Entity* self, const std::string& name) override;
 	void OnActivityTimerUpdate(Entity* self, const std::string& name, float_t timeRemaining, float_t elapsedTime) override;
+	void OnRequestActivityExit(Entity* self, LWOOBJID player, bool canceled);
```
Comment (EmosewaMC) [inline dScripts/ai/MINIGAME/SG_GF/SERVER/SGCannon.h:70]: `override`

File: dGame/dGameMessages/GameMessages.cpp (hunk 1 above)
Comment (aronwk-aaron) [reply dGame/dGameMessages/GameMessages.cpp:6219]: The only other place I saw it being sent was in roller component, which we don't have implemented, but I'll double check

Comment (EmosewaMC) [reply dGame/dGameMessages/GameMessages.cpp:6219]: I'd double check integration testing just in case imo.  Not all GMs are sent from the client exe, some are sent straight from lua, straight from flash etc and the GM call would not be visible in the client (assuming you just looked for references to the function in the client and not in flash/lua)

Comment (aronwk-aaron) [reply dGame/dGameMessages/GameMessages.cpp:6219]: Lua scripts only used it in sg and old racing

**Review by EmosewaMC — APPROVED** [review]

**Review by DarwinAnim8or — APPROVED** [review]
