### PR TITLE
Fix Wingreaper birds not moving

### LINKED ISSUE #1030: BUG: Wingreaper owls do not move
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

72ca0f1

### Issue Description

Wingreaper owls no longer move.

### Reproduction Steps

Use the Assembly Summoner's Wingreaper owl ability. The owls can attack but no longer fly around.

### Expected Behavior

they should fly up to nearby enemies (though they teleported previously).

### Environment

ubuntu server

### PR DESCRIPTION
**Pull request by EmosewaMC**
Fixes #1030 

The client seems to do the following for getting the speed from the ControllablePhysics table (of which there is only ever 1 fetch of this field and it is in a ControllablePhysicsComponent):
Default speed set to 10.0f
Check the PhysicsComponent table for the column speed and if it exists set speed to that value and if the value was null set it to the default again.

Tested that the birds of the Wingreaper now properly move towards their enemy.  Tested that the dragons in Forbidden Valley dragon battle still do not move (since they have null speed too).  Tested that enemies with specifically zero speed remain at zero speed as set in their PhysicsComponent entry.

### CODE REVIEW

File: dGame/dComponents/MovementAIComponent.cpp [hunk 1]
```diff
@@ -307,13 +307,12 @@ float MovementAIComponent::GetBaseSpeed(LOT lot) {
...
+	float speed = 10.0f;
 
-	if (physicsComponent == nullptr) {
-		speed = 8;
-	} else {
-		speed = physicsComponent->speed;
-	}
+	if (physicsComponent) speed = physicsComponent->speed;
+
+	if (speed == -1.0f) speed = 10.0f;
```
Comment (Wincent01) [inline dGame/dComponents/MovementAIComponent.cpp:315]: Not done regularly throughout the codebase, but an abs check would be best.

**Review by Wincent01 — APPROVED** [review]
Good! One non-blocking note.

**Review by aronwk-aaron — DISMISSED** [review]

**Review by aronwk-aaron — APPROVED** [review]

**Review by aronwk-aaron — APPROVED** [review]

**Review by DarwinAnim8or — APPROVED** [review]
