### PR TITLE
fix: Nexus Tower Combat Challenge can be started twice if two players start it at the same time

### LINKED ISSUE #1135: BUG: Nexus Tower Combat Challenge can be started twice if two players start it at the same time
### Make sure you've done the following:

- [X] I have checked that this issue has not already been reported.

- [X] I have validated that this issue is not a syntax error of either MySQL or SQLite.

- [X] I have pulled the latest version of the main branch of DarkflameServer and have confirmed that the issue exists there.

### DarkflameServer Version

All

### Issue Description

If two players start the combat challenge at the same time, the game will be started twice with two dummies spawning.  This causes the initial starter to not be saved and makes it so the extra spawned dummy does nothing except spawn the next dummy in the list, terminating this spawning when the player who started the bugged instance leaves the zone and the dummy dies.

### Reproduction Steps

1) have two players with the window to start the combat challenge open at the same time
2) have both players start at the same time
3) Observe that there are two sets of dummies.

### Expected Behavior

Only initial player who started the game has its dummies spawn

### Environment

All

### PR DESCRIPTION
**Pull request by TAHuntling**
DESC: Fix for dual instance starting when two players hit start on the challenge at the same time.

MOTIVATION: Want to fix issue for any future occurances

TESTING: Will test tomorrow/later

Fixes #1135

### CODE REVIEW

File: dScripts/02_server/Map/NT/NtCombatChallengeServer.cpp [hunk 1]
```diff
@@ -43,7 +43,7 @@ void NtCombatChallengeServer::OnFireEventServerSide(Entity* self, Entity* sender
 
 
 void NtCombatChallengeServer::OnMessageBoxResponse(Entity* self, Entity* sender, int32_t button, const std::u16string& identifier, const std::u16string& userData) {
-	if (identifier == u"PlayButton" && button == 1) {
+	if (identifier == u"PlayButton" && button == 1 && !self->GetVar<bool>(u"bInUse")) {
```
Comment (Wincent01) [inline dScripts/02_server/Map/NT/NtCombatChallengeServer.cpp:46]: The variable in this case is a network variable, which is separate from the normal once. This will have to use the GetNetworkVar variant on the method.

Comment (EmosewaMC) [reply dScripts/02_server/Map/NT/NtCombatChallengeServer.cpp:46]: Oh interesting, I must have mis-read the API.  Should be a simple fix :)

**Review by aronwk-aaron — APPROVED** [review]

**Review by EmosewaMC — APPROVED** [review]
